#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = nm-applet &
exec-once = waybar & hyprpaper

# Dark mode stuff
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'

# Hypridle
exec-once = hypridle

# Hyprsunset
exec-once = hyprsunset

# Start cliphist
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = $HOME/dotfiles/shared/hypr/scripts/cliphist-watch.sh

# Notifications + panel thing
exec-once = swaync

# Wallpapers
exec-once = $HOME/dotfiles/shared/hypr/scripts/random-wall.sh

# Walker launcher
exec-once = walker --gapplication-service

exec-once = elephant service enable
exec-once = systemctl --user start elephant.service
