exec-once = hyprpm reload -n

plugin {
  split-monitor-workspaces {
    count = 5
    keep_focused = 0
    enable_notifications = 1
    enable_persistent_workspaces = 1
    enable_wrapping = 1

    # set this to 1 for gnome-like workspace switching
    link_monitors = 0

    # set this to 0 to disable hy3 support
    # enable_hy3 = 1
    # set monitor priority (first = lowest workspace numbers)
    monitor_priority = DP-1, HDMI-A-1
    # set max workspaces per monitor
    max_workspaces = DP-1,    5
    max_workspaces = HDMI-A-1,5
  }
}

exec-once = hyprland-autoname-workspaces
