# ── Shared ────────────────────────────────────────────────────────────────────
source = ./conf/env.conf
source = ./conf/permissions.conf
source = ./conf/programs.conf
source = ./conf/autostart.conf
source = ./conf/look_and_feel.conf
source = ./conf/input.conf
source = ./conf/binds.conf
source = ./conf/windows_and_workspaces.conf
source = ./conf/plugins.conf

# ── Host overrides ────────────────────────────────────────────────────────────
# IMPORTANT: host overrides need to come from dotfiles/hosts/HOSTNAME/hypr/...
